# Generated by Django 2.2.7 on 2019-11-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20191106_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='carrera',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cedula_profesional',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='domicilio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='nombre_instructor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
