# Generated by Django 2.2.7 on 2019-11-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_auto_20191106_0246'),
        ('instructor', '0004_auto_20191106_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='matrix',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
    ]
