# Generated by Django 2.2.7 on 2019-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo_electronico',
            field=models.CharField( max_length=25),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dirrecion',
            field=models.CharField( max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_empleado',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
