# Generated by Django 2.2.7 on 2019-11-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20191106_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default='15'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_empleado',
            field=models.IntegerField(default='0'),
        ),
    ]
