# Generated by Django 2.2.7 on 2019-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20191106_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_empleado',
            field=models.IntegerField(default=1),
        ),
    ]
