# Generated by Django 2.2.7 on 2019-11-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_auto_20191106_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
