# Generated by Django 2.2.7 on 2019-11-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_auto_20191106_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo_electronico',
            field=models.CharField( max_length=25),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dirrecion',
            field=models.CharField( max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField( max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField( max_length=10),
        ),
    ]
