# Generated by Django 2.2.7 on 2019-11-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_auto_20191106_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo_electronico',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dirrecion',
            field=models.CharField(max_length=40),
        ),
    ]
