# Generated by Django 2.2.7 on 2019-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreza', '0006_auto_20191106_0246'),
        ('alumno', '0009_auto_20191106_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='empreza_matrix',
            field=models.ManyToManyField(to='empreza.Empreza'),
        ),
    ]
