# Generated by Django 2.2.7 on 2019-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='curso',
            name='numero_curso',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo_curso',
            field=models.CharField(default='Type here', max_length=30),
        ),
    ]
