# Generated by Django 2.2.7 on 2019-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20191106_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='numero_curso',
            field=models.IntegerField(default=1),
        ),
    ]
