# Generated by Django 2.2.7 on 2019-11-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20191106_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero_curso',
            field=models.IntegerField(),
        ),
    ]
