# Generated by Django 2.2.7 on 2019-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_instructor_matrix'),
        ('curso', '0006_auto_20191106_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso_profesor',
            field=models.ManyToManyField(to='instructor.Instructor'),
        ),
    ]
