# Generated by Django 2.2.7 on 2019-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreza',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empreza',
            name='domicilio',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='empreza',
            name='nombre_empresa',
            field=models.TextField(default='Type here'),
        ),
        migrations.AddField(
            model_name='empreza',
            name='rfc',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='empreza',
            name='telefono',
            field=models.CharField(default='Type here', max_length=10),
        ),
    ]
