# Generated by Django 2.2.7 on 2019-11-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreza', '0003_auto_20191106_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreza',
            name='domicilio',
            field=models.CharField(default='Type', max_length=30),
        ),
        migrations.AlterField(
            model_name='empreza',
            name='nombre_empresa',
            field=models.CharField(default='Type', max_length=30),
        ),
        migrations.AlterField(
            model_name='empreza',
            name='rfc',
            field=models.CharField(default='Type', max_length=30),
        ),
        migrations.AlterField(
            model_name='empreza',
            name='telefono',
            field=models.CharField(default='Type', max_length=10),
        ),
    ]
