# Generated by Django 2.2.7 on 2019-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreza', '0004_auto_20191106_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreza',
            name='rfc',
            field=models.CharField(max_length=30),
        ),
    ]
